apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopkart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopkart
  template:
    metadata:
      labels:
        app: shopkart
    spec:
      containers:
        - name: shopkart-container
          image: shopkart:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: shopkart-service
spec:
  selector:
    app: shopkart
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
